version: '3.9'

services:
  fleet-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
          MODULE: fleet-service
    container_name: fleet-service
    env_file: [ .env ]
    ports:
      - "${FLEET_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://tpi-db:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}

    depends_on: [ db, keycloak ]


  orders-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
       MODULE: orders-service
    container_name: orders-service
    env_file: [ .env ]
    ports:
      - "${ORDER_PORT}:8101"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://tpi-db:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      KEYCLOAK_URL: ${KEYCLOAK_URL}

    depends_on: [ db, keycloak ]


  db:
    image: postgres:15
    container_name: tpi-db
    env_file: [ .env ]
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/postgresql/data


  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    command: start-dev
    env_file: [ .env ]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASS}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile.service
      args:
        MODULE: gateway-service
    container_name: gateway-service
    ports:
      - "${GATEWAY_PORT}:8080"
    env_file:
      - .env
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
    depends_on:
      - fleet-service
      - orders-service
      - keycloak


volumes:
  db_data:
  keycloak_data:









