# Etapa 1: build (multi-módulo sin depender del reactor)
FROM maven:3.9.6-eclipse-temurin-17 AS builder
ARG MODULE
WORKDIR /workspace

# Copiamos TODO el proyecto (pom padre + módulos)
COPY . .

# Nos paramos dentro del módulo y build directo
WORKDIR /workspace/${MODULE}
RUN mvn clean package -DskipTests

# Etapa 2: run
FROM eclipse-temurin:17-jdk
ARG MODULE
WORKDIR /app
COPY --from=builder /workspace/${MODULE}/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
