server:
  port: 8080

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}

  cloud:
    gateway:
      routes:
        # RUTA A ORDERS
        - id: orders-service
          uri: http://orders-service:8101
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1

        # RUTA A FLEET
        - id: fleet-service
          uri: http://fleet-service:8080
          predicates:
            - Path=/fleet/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always

